[package]
name = "irc_proto"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
itertools = "0.12.1"
nom = "7.1"
thiserror = "1.0.30"

[lints]
workspace = true
