[general]
background = "#333333"
horizontal_rule = "#333333"
unread_indicator = "#2884fc"
border = "#505050"

[text]
primary = "#dfdfdf"
secondary = "#c2c2c2"
tertiary = "#8839ef"
success = "#959595"
error = "#959595"

[buffer]
background = "#1e1e1e"
background_text_input = "#2e2e2e"
background_title_bar = "#2e2e2e"
timestamp = "#959595"
action = "#959595"
topic = "#dfdfdf"
highlight = "#454645"
code = "#7287fd"
nickname = "#00c8ff"
url = "#2884fc"
selection = "#777777"
border_selected = "#1a1a1a"
border = "#1a1a1a"

[buffer.server_messages]
default = "#959595"

[buttons.primary]
background_hover = "#484848"
background_selected = "#4a4a4a"
background_selected_hover = "#666666"

[buttons.secondary]
background = "#3b3b3b"
background_hover = "#484848"
background_selected = "#646464"
background_selected_hover = "#666666"
