name: Build

on:
  pull_request:
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - 'Cargo.lock'
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - 'Cargo.lock'
  merge_group:
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - 'Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  Check-Clippy-Test:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C linker=clang -C link-arg=-fuse-ld=mold"
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install \
          build-essential \
          git \
          pkg-config \
          mold \
          clang \
          libdbus-1-dev \
          libudev-dev \
          libxkbcommon-dev \
          libfontconfig1-dev \
          libasound2-dev
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Check
      run: cargo check --profile ci
    - name: Clippy
      run: cargo clippy --profile ci --workspace --all-targets -- -D warnings
    - name: Test
      run: cargo test --profile ci --workspace --all-targets
  spelling:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Spell Check Repository
        uses: crate-ci/typos@v1.32.0
